### ISSUE TITLE
fZooMSS_Project.R

### ISSUE THREAD

**Issue by ric325** [MathMarEcol/ZoopModelSizeSpectra#14]
I think this should be renamed so we don't think it is an R Project. What about calling it: 

fZooMSS_Run.R
or 
fZooMSS_Simulation.R

**Comment by jaseeverett** [comment]
Agreed. Done. 
But note you are recording these in the wrong Repo. Use https://github.com/MathMarEcol/ZooMSS/issues instead

**Comment by ric325** [comment]
I did I thought? How have you seen them?

**Comment by jaseeverett** [comment]
Because I get an email when a comment is left in any of our repos.

This is the public Repo, not the ZooMSS one we are using for development
